name: Generar jornada automática

on:
  workflow_dispatch:  
  schedule:
    - cron: "0 8 * * *"   

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false   

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install --upgrade pip

      - name: Ejecutar script
        run: python generar_jornada_normal.py
   
      - name: Commit y push de cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add datos.json
          git commit -m "Añadir jornada automáticamente [skip ci]" || echo "No hay cambios"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
